services:
  flask_app:
    env_file:
      - ".env"
    build: ./app
    ports:
      - "5001:5000"
    environment:
      - FLASK_ENV=development
    restart: always
    volumes:
      - ./app/logs:/app/logs
